# docker-compose.yml

version: "2"
services:
  swagger:
    image: "swaggerapi/swagger-ui"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://192.168.0.120:3000/
